trigger:
  branches:
    include:
      - main

pool:
  name: Default

stages:
- stage: BuildAndTest
  jobs:
  - job: AngularJob
    steps:
    - task: NodeTool@0
      displayName: 'Install Node.js'
      inputs:
        versionSpec: '20.x'  

    - task: Npm@1
      displayName: 'Install Angular CLI globally'
      inputs:
        command: 'custom'
        customCommand: 'install -g @angular/cli'

    - task: Npm@1
      displayName: 'Install project dependencies'
      inputs:
        command: 'install'

    - task: Npm@1
      displayName: 'Run Unit Tests with coverage'
      inputs:
        command: 'custom'
        customCommand: 'run test -- --watch=false --browsers=ChromeHeadless'
 
    - script: |
        npm run test -- --watch=false --browsers=ChromeHeadless --code-coverage
      displayName: 'Run Unit Tests with Coverage'

  
    - script: |
        npx lcov-to-cobertura-xml coverage/lcov.info
      displayName: 'Convert LCOV to Cobertura XML'


   - task: PublishTestResults@2
      displayName: 'Publish Test Results'
      condition: succeededOrFailed()
      inputs:
        testResultsFormat: 'JUnit'
        testResultsFiles: '**/TESTS-results.xml'
        searchFolder: '$(System.DefaultWorkingDirectory)'
        mergeTestResults: true

   - task: PublishCodeCoverageResults@1
      displayName: 'Publish Code Coverage'
      inputs:
        codeCoverageTool: 'Cobertura'
        summaryFileLocation: 'coverage/cobertura-coverage.xml'
        reportDirectory: 'coverage/customer-app' 
        failIfCoverageEmpty: true

    - task: Npm@1
      displayName: 'Build Angular App'
      inputs:
        command: 'custom'
        customCommand: 'run build'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish Artifacts'
      inputs:
        PathtoPublish: 'dist'  
        ArtifactName: 'drop'
        publishLocation: 'Container'
